
# Configuración base de colores
background #0D0D0D
foreground #F2E0D0
selection_background #735D63
selection_foreground #F2E0D0

# Cursor
cursor #F2D22E
cursor_text_color background

# Paleta de colores
color0 #0D0D0D
color8 #655555

color1 #735D63
color9 #735D63

color2 #F2D22E
color10 #F2D22E

color3 #F2E0D0
color11 #F2E0D0

# Opacidad
background_opacity 0.85
